// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn59OmjrRPpkgg1WEmIqcj-161lYfj2sw',
    appId: '1:70870536138:web:e563178513d539fcc94933',
    messagingSenderId: '70870536138',
    projectId: 'prize-bond-app-3a0b2',
    authDomain: 'prize-bond-app-3a0b2.firebaseapp.com',
    storageBucket: 'prize-bond-app-3a0b2.firebasestorage.app',
    measurementId: 'G-BVCN0PGB3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfFE5bMDxBXPJGq51WT-Tv75NLZoilKaY',
    appId: '1:70870536138:android:47e3a5b8e7c097a9c94933',
    messagingSenderId: '70870536138',
    projectId: 'prize-bond-app-3a0b2',
    storageBucket: 'prize-bond-app-3a0b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-8O6tJHOMUAuAzhwGa0SAWiS9_k5BFGg',
    appId: '1:70870536138:ios:1c8b9676c6386b28c94933',
    messagingSenderId: '70870536138',
    projectId: 'prize-bond-app-3a0b2',
    storageBucket: 'prize-bond-app-3a0b2.firebasestorage.app',
    iosBundleId: 'com.example.prizeBondApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-8O6tJHOMUAuAzhwGa0SAWiS9_k5BFGg',
    appId: '1:70870536138:ios:1c8b9676c6386b28c94933',
    messagingSenderId: '70870536138',
    projectId: 'prize-bond-app-3a0b2',
    storageBucket: 'prize-bond-app-3a0b2.firebasestorage.app',
    iosBundleId: 'com.example.prizeBondApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn59OmjrRPpkgg1WEmIqcj-161lYfj2sw',
    appId: '1:70870536138:web:2f4a1062ade87539c94933',
    messagingSenderId: '70870536138',
    projectId: 'prize-bond-app-3a0b2',
    authDomain: 'prize-bond-app-3a0b2.firebaseapp.com',
    storageBucket: 'prize-bond-app-3a0b2.firebasestorage.app',
    measurementId: 'G-YYCHTMW2Q5',
  );
}
